name: smoke
description: "Smoke - we sell tobacco accessories"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3

  # State management
  get: ^4.6.6

  # Icons
  font_awesome_flutter: ^10.7.0

  # Carousel
  carousel_slider: ^5.0.0
  flutter_layout_grid: ^2.0.7

  # Text
  readmore: ^3.0.0

  # Star rating
  flutter_rating_bar: ^4.0.1
  flutter_rating_stars: ^1.1.0

  # Storage
  get_storage: ^2.1.1

  # Splash
  flutter_native_splash: ^2.4.4

  # Firebase
  firebase: ^9.0.3
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.2

  # Lottie
  lottie: ^3.0.0

  # Utils
  logger: ^2.5.0
  cloud_firestore: ^5.6.2
  intl: ^0.20.2
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Splash
flutter_native_splash:
  color: "#89AC46"
  color_dark: "#272727"
  image: assets/logos/logo-black.png
  image_dark: assets/logos/logo-white.png

  android_12:
    color: "#89AC46"
    color_dark: "#272727"
    image: assets/logos/logo-black.png
    image_dark: assets/logos/logo-white.png

flutter:
  # uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/images/animations/
