name: single_store_ecommerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3

  # State management
  get: ^4.6.6

  # Icons
  font_awesome_flutter: ^10.7.0

  # Carousel
  carousel_slider: ^5.0.0
  flutter_layout_grid: ^2.0.7

  # Text
  readmore: ^3.0.0

  # Star rating
  flutter_rating_bar: ^4.0.1

  # Storage
  firebase_core: ^3.10.1
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.4
  firebase: ^9.0.3
  firebase_core_platform_interface: ^5.4.0
  firebase_auth: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/
