name: single_store_ecommerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3

  # State management
  get: ^4.6.6

  # Icons
  font_awesome_flutter: ^10.7.0

  # Carousel
  carousel_slider: ^5.0.0
  flutter_layout_grid: ^2.0.7

  # Text
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/images/content/
